const router = require('express').Router();
const c = require('../controllers/productController');
const { auth, requireRole } = require('../middleware/auth');
const upload = require('../middleware/upload');
router.get('/', c.list);
router.get('/:id', c.detail);
router.post('/', auth, requireRole('seller'), upload.array('productImages', 6), c.create);
router.post('/:id/bid', auth, c.bid);
router.post('/:id/buy-now', auth, c.buyNow);
module.exports = router;
